# Day 13 科学计算库Numpy的常用函数(二)

In [1]:
import numpy as np
# 导入模块

## 1、Numpy中数组堆叠

### numpy.hstack(tup)：水平（按列顺序）堆叠数组

In [2]:
a1 = np.arange(5)        # a1为一维数组，5个元素
b1 = np.arange(5,9)      # b1为一维数组,4个元素
ar1 = np.hstack((a1,b1))  # 注意:((a1,b1))，这里形状可以不一样
print(a1,a1.shape)
print(b1,b1.shape)
print(ar1,ar1.shape)

[0 1 2 3 4] (5,)
[5 6 7 8] (4,)
[0 1 2 3 4 5 6 7 8] (9,)


In [3]:
a2 = np.array([[0],[1],[2]])        # a2为二维数组，3行1列
b2 = np.array([['a'],['b'],['c']])  # b2为二维数组，3行1列
ar2 = np.hstack((a2,b2))             # 注意:((a2,b2))，这里形状必须一样
print(a2,a2.shape)
print(b2,b2.shape)
print(ar2,ar2.shape)

[[0]
 [1]
 [2]] (3, 1)
[['a']
 ['b']
 ['c']] (3, 1)
[['0' 'a']
 ['1' 'b']
 ['2' 'c']] (3, 2)


### numpy.vstack(tup)：垂直（按列顺序）堆叠数组

In [4]:
a3 = np.arange(5)      # a3为一维数组，5个元素
b3 = np.arange(5,10)   # b3为一维数组,4个元素
ar3 = np.vstack((a3,b3))
print(a3,a3.shape)
print(b3,b3.shape)
print(ar3,ar3.shape)

[0 1 2 3 4] (5,)
[5 6 7 8 9] (5,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


In [5]:
a4 = np.array([[0],[1],[2]])              # a4为二维数组，3行1列
b4 = np.array([['a'],['b'],['c'],['d']])  # b4为二维数组，4行1列 
ar4 = np.vstack((a4,b4))                  # 这里形状可以不一样
print(a4,a4.shape)
print(b4,b4.shape)
print(ar4,ar4.shape)

[[0]
 [1]
 [2]] (3, 1)
[['a']
 ['b']
 ['c']
 ['d']] (4, 1)
[['0']
 ['1']
 ['2']
 ['a']
 ['b']
 ['c']
 ['d']] (7, 1)


### numpy.stack(arrays, axis=0)：沿着新轴连接数组的序列，形状必须一样！

In [6]:
a5 = np.arange(5)    
b5 = np.arange(5,10)
ar5_1 = np.stack((a5,b5))
ar5_2 = np.stack((a5,b5),axis = 1)
print(a5,a5.shape)
print(b5,b5.shape)
print(ar5_1,ar5_1.shape)
print(ar5_2,ar5_2.shape)
# axis参数：假设两个数组[1 2 3]和[4 5 6]，shape均为(3,0)，默认axis等于0
# axis=0：[[1 2 3] [4 5 6]]，shape为(2,3)
# axis=1：[[1 4] [2 5] [3 6]]，shape为(3,2)

[0 1 2 3 4] (5,)
[5 6 7 8 9] (5,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] (5, 2)


## 2、Numpy中数组拆分

### numpy.hsplit(ary, indices_or_sections)：将数组水平（逐列）拆分为多个子数组——按列拆分

In [7]:
ar6 = np.arange(16).reshape(4,4)
ar7 = np.hsplit(ar6,2)
print(ar6)
print(ar7,type(ar7))
# 输出结果为列表，列表中元素为数组

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] <class 'list'>


### numpy.vsplit(ary, indices_or_sections)：将数组垂直（行方向）拆分为多个子数组——按行拆

In [8]:
ar8 = np.arange(16).reshape(4,4)
ar9 = np.vsplit(ar8,4)
print(ar8)
print(ar9,type(ar9))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])] <class 'list'>


## 3、Numpy中数组简单运算

In [9]:
ar = np.arange(6).reshape(2,3)
print(ar)

[[0 1 2]
 [3 4 5]]


In [10]:
# 与标量的运算

print(ar + 10)   # 加法
print(ar * 2)   # 乘法
print(1 / (ar+1))  # 除法
print(ar ** 0.5)  # 幂

[[10 11 12]
 [13 14 15]]
[[ 0  2  4]
 [ 6  8 10]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]


In [11]:
# 常用函数

print(ar.mean())  # 求平均值
print(ar.max())  # 求最大值
print(ar.min())  # 求最小值
print(ar.std())  # 求标准差
print(ar.var())  # 求方差
print(ar.sum(), np.sum(ar,axis = 0))  # 求和，np.sum()：axis为0，按列求和；axis为1，按行求和
print(np.sort(np.array([1,4,3,2,5,6])))  # 排序

2.5
5
0
1.707825127659933
2.9166666666666665
15 [3 5 7]
[1 2 3 4 5 6]
