# Day 10 科学计算库Numpy的索引与切片

In [1]:
# 导入模块

import numpy as np

## 1、Numpy中基本索引与切片

In [2]:
# 一维数组的索引与切片

ar1 = np.arange(10)
print(ar1)
print(ar1[5])
print(ar1[3:8])

[0 1 2 3 4 5 6 7 8 9]
5
[3 4 5 6 7]


In [3]:
# 二维数组的索引与切片

ar2 = np.arange(16).reshape(4,4)
print(ar2, '数组轴数为%i' %ar2.ndim)              # 显示4*4的数组，并显示数组的轴数
print('---------------------------')
print(ar2[2],  '数组轴数为%i' %ar2[2].ndim)      # 一次索引，相当于切片，将原数组降维，所以这里是一个一维数组
print('---------------------------')
print(ar2[2][1])                                # 二次索引，则再得到一维数组中的一个值
print('---------------------------')
print(ar2[1:3],  '数组轴数为%i' %ar2[1:3].ndim)   # 切片选取其中的两个一维数组组成一个二维数组
print('---------------------------')
print(ar2[2,2])                                 # 切片数组中的第三行第三列是10
print('---------------------------')
print(ar2[:2,1:])                               # 切片取出数组中的1,2行、2,3,4列来组成二维数组

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 数组轴数为2
---------------------------
[ 8  9 10 11] 数组轴数为1
---------------------------
9
---------------------------
[[ 4  5  6  7]
 [ 8  9 10 11]] 数组轴数为2
---------------------------
10
---------------------------
[[1 2 3]
 [5 6 7]]


In [4]:
# 三维数组的索引与切片

ar3 = np.arange(8).reshape(2,2,2)
print(ar3, '数组轴数为%i' %ar3.ndim)                     # 2*2*2的数组，并显示数组的轴数
print('---------------------------')
print(ar3[0],  '数组轴数为%i' %ar3[0].ndim)              # 一次索引，三维数组的一个维度的第一个元素是一个二维数组
print('---------------------------')
print(ar3[0][0],  '数组轴数为%i' %ar3[0][0].ndim)        # 二次索引，三维数组的一个维度的第一个元素下的第一个元素是一个一维数组
print('---------------------------')
print(ar3[0][0][1],  '数组轴数为%i' %ar3[0][0][1].ndim)  # 三次索引

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 数组轴数为3
---------------------------
[[0 1]
 [2 3]] 数组轴数为2
---------------------------
[0 1] 数组轴数为1
---------------------------
1 数组轴数为0


## 2、Numpy中布尔型索引与切片

In [5]:
# 布尔型索引：以布尔型的矩阵去做筛选

ar = np.arange(12).reshape(3,4)
i = np.array([True,False,True])
j = np.array([True,True,False,False])
print(ar)
print('---------------------------')
print(i)
print('---------------------------')
print(j)
print('---------------------------')
print(ar[i,:])  # 在第一维度做判断，只保留True，这里第一维度就是行，ar[i,:] = ar[i]（简单书写格式）
print('---------------------------')
print(ar[:,j])  # 在第二维度做判断，这里如果ar[:,i]会有警告，因为i是3个元素，而ar在列上有4个
print('---------------------------')

m = ar > 5
print(m)  # 这里m是一个判断矩阵
print('---------------------------')
print(ar[m])  # 用m判断矩阵去筛选ar数组中>5的元素 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------------------
[ True False  True]
---------------------------
[ True  True False False]
---------------------------
[[ 0  1  2  3]
 [ 8  9 10 11]]
---------------------------
[[0 1]
 [4 5]
 [8 9]]
---------------------------
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
---------------------------
[ 6  7  8  9 10 11]


## 3、数组索引与切片的值的更改、复制

In [6]:
# 一个标量赋值给一个索引/切片时，会自动改变/传播原始数组

ar4 = np.arange(10)
print(ar4)
ar4[5] = 100
print(ar4)
ar4[7:9] = 200
print(ar4)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4 100   6   7   8   9]
[  0   1   2   3   4 100   6 200 200   9]


In [7]:
# 利用.copy方法进行复制，不改变原数组

ar5 = np.arange(10)
b = ar5.copy()
b[7:9] = 200
print(ar5)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3   4   5   6 200 200   9]
