# Day 09 科学计算库Numpy的基础数据结构

NumPy主要是一个用来进行数组相关的科学计算的工具包，其创建的数组是一个多维数组对象，称为ndarray。

其由两部分组成：

1. 实际的数据

2. 描述这些实际数据的元数据

## 1、ndarray的数据类型

bool	用一个字节存储的布尔类型（True或False）

inti	由所在平台决定其大小的整数（一般为int32或int64）

int8	一个字节大小，-128 至 127

int16	整数，-32768 至 32767

int32	整数，-2 ^ 31 至 2 ^ 32 -1

int64	整数，-2 ^ 63 至 2 ^ 63 - 1

uint8	无符号整数，0 至 255

uint16	无符号整数，0 至 65535

uint32	无符号整数，0 至 2 ^ 32 - 1

uint64	无符号整数，0 至 2 ^ 64 - 1

float16	半精度浮点数：16位，正负号1位，指数5位，精度10位

float32	单精度浮点数：32位，正负号1位，指数8位，精度23位

float64或float	双精度浮点数：64位，正负号1位，指数11位，精度52位

complex64	复数，分别用两个32位浮点数表示实部和虚部

complex128或complex	复数，分别用两个64位浮点数表示实部和虚部

## 2、多维数组ndarray的一些基本操作

数组的基本属性

在NumPy中，每一个线性的数组称为是一个轴（axes），秩（rank）其实是描述轴的数量：

比如说，二维数组相当于是两个一维数组，其中第一个一维数组中每个元素又是一个一维数组

所以一维数组就是NumPy中的轴（axes），第一个轴（axes）相当于是底层数组，第二个轴是（axes）底层数组里的数组。

而轴（axes）的数量——秩（rank），就是数组的维数。 

In [1]:
import numpy as np

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
print(ar)
# 输出数组
# 注：数组的格式——有中括号，但元素之间没有逗号（和列表区分）

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(ar.ndim)
# 输出数组维度（轴数），或者说“秩”（rank）

1


In [5]:
print(ar.shape)
# 输出数组的维度，对于n行m列的数组，shape为（n，m）

(10,)


In [6]:
print(ar.size)
# 输出数组的元素总数，对于n行m列的数组，元素总数为n*m

10


In [7]:
print(ar.dtype)
# 输出数组中元素的类型，类似type()
# 注：type()是函数，.dtype是方法

int32


In [8]:
print(ar.itemsize)
# 输出数组中每个元素的字节大小，其中int32类型的字节为4，float64类型的字节为8

4


In [9]:
print(ar.data)
# 包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性

In [10]:
ar
# 交互方式下输出，会有array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3、创建数组的几种常见函数和方法

### array()函数，括号内可以是列表、元祖、数组、生成器等

In [11]:
ar1 = np.array(range(10))                          # 整型
ar2 = np.array([0,1,2,3.14,4,5])                   # 浮点型
ar3 = np.array([ [1,2,3] , ('a','b','c') ])        # 二维数组：嵌套序列（列表，元祖均可）
ar4 = np.array([ [1,2,3] , ('a','b','c','d') ])    # 注意嵌套序列数量不一会怎么样

print(ar1,type(ar1),ar1.dtype)
print(ar2,type(ar2),ar2.dtype)

print(ar3,ar3.shape,ar3.ndim,ar3.size)             # 二维数组，共6个元素
print(ar4,ar4.shape,ar4.ndim,ar4.size)             # 一维数组，共2个元素

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32
[0.   1.   2.   3.14 4.   5.  ] <class 'numpy.ndarray'> float64
[['1' '2' '3']
 ['a' 'b' 'c']] (2, 3) 2 6
[list([1, 2, 3]) ('a', 'b', 'c', 'd')] (2,) 1 2


### arange()，类似range()，在给定间隔区域内返回均匀间隔的值

In [12]:
print(np.arange(10))              # 返回0-9，整型
print(np.arange(10.0))            # 返回0.0-9.0，浮点型
print(np.arange(3,11))            # 返回3-10
print(np.arange(3.0,11,2))        # 返回3.0-11.0（不取11.0），步长为2
print(np.arange(10000))           # 如果数组太大而无法打印，NumPy会自动跳过数组的中心部分，并只打印边角：

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 3  4  5  6  7  8  9 10]
[3. 5. 7. 9.]
[   0    1    2 ... 9997 9998 9999]


### linspace()，返回在间隔 $[开始，停止]$ 上计算的num个均匀间隔的样本

In [13]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# start：起始值，stop：结束值
# num：生成样本数，默认为50
# endpoint：如果为真，则停止是最后一个样本。否则，不包括在内。默认值为True。
# retstep：如果为真，返回（样本，步骤），其中步长是样本之间的间距 → 输出为一个包含2个元素的元祖，第一个元素为array，第二个为步长实际值

ar5 = np.linspace(1.0, 5.0)
ar6 = np.linspace(1.0, 5.0, num=5)
ar7 = np.linspace(1.0, 5.0, num=5, endpoint=False)
ar8 = np.linspace(1.0, 5.0, num=5, retstep=True)
print(ar5,type(ar5))
print(ar6,type(ar6))
print(ar7,type(ar7))
print(ar8,type(ar8))

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ] <class 'numpy.ndarray'>
[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>
[1.  1.8 2.6 3.4 4.2] <class 'numpy.ndarray'>
(array([1., 2., 3., 4., 5.]), 1.0) <class 'tuple'>


### zeros()/zeros_like()/ones()/ones_like()

In [14]:
# numpy.zeros(shape, dtype=float, order='C'):返回给定形状和类型的新数组，用零填充。
# shape：数组纬度，二维以上需要用()，且输入参数为整数
# dtype：数据类型，默认numpy.float64
# order：是否在存储器中以C或Fortran连续（按行或列方式）存储多维数据。

ar9 = np.zeros(5)  
ar10 = np.zeros((3,4), dtype = np.int)
print(ar9,ar9.dtype)
print(ar10,ar10.dtype)

[0. 0. 0. 0. 0.] float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] int32


In [15]:
# zeros_like():返回具有与给定数组相同的形状和类型的零数组，这里ar12根据ar11的形状和dtype创建一个全0的数组

ar11 = np.array([ list(range(10)) , list(range(10,20)) ])
ar12 = np.zeros_like(ar11)
print(ar11,type(ar11))
print(ar12,type(ar12))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] <class 'numpy.ndarray'>
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] <class 'numpy.ndarray'>


In [16]:
# ones()/ones_like():和zeros()/zeros_like()一样，只是填充的数字不是0，而是1

ar13 = np.array([ list(range(10)) , list(range(10,20)) ])
ar14 = np.ones(9)
ar15 = np.ones((3,4,5))
ar16 = np.ones_like(ar13)
print(ar13)
print(ar14)
print(ar15)
print(ar16)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


### eye()，创建一个正方形的N*N的单位矩阵，对角线值为1，其余为0

In [17]:
print(np.eye(6))
# 创建一个正方的6*6的单位矩阵，对角线值为1，其余为0

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
