# Day 12 科学计算库Numpy的常用函数(一)

In [1]:
import numpy as np
# 导入模块

## 1、Numpy中数组形状的操作

.T/.reshape()/.resize()

### .T方法：转置

In [2]:
# 例如：原shape为(3,4)，转置结果为(4,3) ； 原shape为(2,3,4)，转置结果为(4,3,2)
# 一维数组转置后结果不变

ar1 = np.arange(10)
ar2 = np.ones((5,2))
print(ar1,'\n',ar1.T)
print(ar2,'\n',ar2.T)

[0 1 2 3 4 5 6 7 8 9] 
 [0 1 2 3 4 5 6 7 8 9]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### .reshape方法：改变形状

In [3]:
# 用法1：直接将已有数组改变形状

ar3 = np.arange(10)
ar4 = ar3.reshape(2,5)
print(ar3,'\n',ar4)

[0 1 2 3 4 5 6 7 8 9] 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
# 用法2：生成数组后直接改变形状

ar5 = np.zeros((4,6)).reshape(3,8)
print(ar5)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
# 用法3：参数内添加数组，目标形状

ar6 = np.reshape(np.arange(12),(3,4))
print(ar6)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### .resize方法：改变形状，生成新数组

In [6]:
# numpy.resize(a, new_shape)：返回具有指定形状的新数组，如有必要可重复填充所需数量的元素

ar7 = np.resize(np.arange(5),(3,4))
print(ar7)

[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]


注：

numpy.reshape(a, newshape, order='C')：为数组提供新形状，而不更改其数据，所以元素数量需要一致

.T/.reshape()/.resize()都是生成新的数组

## 2、Numpy中数组的复制

In [7]:
ar8 = np.arange(10)
ar9 = ar8
print(ar9 is ar8)
ar8[2] = 9
print(ar8)
print(ar9)
# python的赋值逻辑：指向内存中生成的一个值:这里ar8和ar9指向同一个值，所以ar8改变，ar9一起改变

True
[0 1 9 3 4 5 6 7 8 9]
[0 1 9 3 4 5 6 7 8 9]


In [8]:
ar10 = np.arange(10)
ar11 = ar10.copy()
print(ar11 is ar10)
ar10[0] = 9
print(ar10)
print(ar11)
# .copy方法生成数组及其数据的完整拷贝:ar10改变，ar11不一起改变

False
[9 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## 3、Numpy中数组类型转换：.astype()

In [9]:
# 可以在参数位置设置数组类型
ar12 = np.arange(10,dtype=float)
print(ar12,ar12.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [10]:
# a.astype()：转换数组类型
ar13 = np.arange(10,dtype=float)
ar14 = ar13.astype(np.int32)
print(ar13,ar13.dtype)
print(ar14,ar14.dtype)
# 注意：数组类型用np.int32，而不是直接int32

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int32
